[package]
name = "cli"
version = "0.3.0"
edition = "2021"

[dependencies]
cookie.workspace = true
serde.workspace = true
serde_json.workspace = true

gateau = { path = "../gateau" }

http = "^1.1.0"
bpaf = { version = "^0.9.14", features = ["derive", "bright-color"] }
color-eyre = "^0.6.2"
itertools = { version = "^0.13.0", optional = true }
tempfile = "3.3.0"

[features]
default = []
human = ["dep:itertools"]
bundled = ["gateau/bundled"]
wasm = ["gateau/wasm"]
